/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Mon Mar 16 12:19:17 2020"
#define BUILD_TIME (1584375557L)

#define VERSION_NUMBER 0x00000707UL
#define VERSION_FEATURES 0x001fee4cUL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x44218263UL
#define VERSION_SANITY2 0xb8d28978UL

#define VERSION_STRING "0.0.7E7F2"
#define VERSION_ID \
 "Unix SlashEM Version 0.0.7E7F2 - last build Mon Mar 16 12:19:17 2020."
